# Generated by Django 4.1.5 on 2023-01-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='binray',
            field=models.BinaryField(max_length=20, null=True),
        ),
    ]
