# Generated by Django 4.1.5 on 2023-01-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_binray'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='binray',
        ),
        migrations.AddField(
            model_name='product',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
