# Generated by Django 4.1.5 on 2023-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
