# Generated by Django 4.1.5 on 2023-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_is_avaliable_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ph', 'Phone'), ('cm', 'Camera')], max_length=50, null=True),
        ),
    ]
